file:
  mode: local # only local
  dir: C://jsolution/jagency # 파일 저장 경로
  target: http://localhost:18032

mifare:
  use: true # true: acr122 사용, false: acr122 사용 안함

  secret-key: FFFFFFFFFFFF
  debug: true


app:
  file-server-host: http://192.168.0.39:18010
  #    file-path: C://jsolution/jagency # 앱 파일 저장 경로
  file-path: /Volumes/extssd/jsolution # 앱 파일 저장 경로
  #  extension-id: jagency # 앱 ID
  version-url: /api/open/extensions/version/jagency # 앱 다운로드 URL
  download-url: /api/open/extensions/download/jagency # 앱 다운로드 URL

  tag:
    endpoint: /api/v1/room-waitings/tag
    roomId: 1
