server:
  port: 5114
# build gradle에서 가져온 properties 값

# 파일 변경 시 필수적으로 변경해줘야 함.
# 혹시나 변경 못 했다면 파일 실행할때 수정해줘야 하는데..
# 배치 파일은 변경하기 힘듦! 꼭 변경해야 함
ext:
  appVersion : 1.2.07 # 전송 후 마지막 보낸 버전 업데이트 바람
api:
  url:
    health:
      tag: /api/v2/health/tag

---
spring:
  profiles:
    active: bonwon

---
spring:
  config:
    activate:
      on-profile: "bonwon"

server:
  port: 5114

---
spring:
  config:
    activate:
      on-profile: "chilgok"

server:
  port: 5114