server:
  port: 5114
# build gradle에서 가져온 properties 값
ext:
  appVersion : 1.02


---
spring:
  profiles:
    active: bonwon

---
spring:
  config:
    activate:
      on-profile: "bonwon"

server:
  port: 5114

---
spring:
  config:
    activate:
      on-profile: "chilgok"

server:
  port: 5114


