server:
  port: ${PORT:18032}
  tomcat:
    remoteip:
      protocol-header: x-forwarded-proto
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s

app:
  version: 0.2.0 # 앱 버전, 서버에 저장된 최신 버전 다운로드시 사용한다.

springdoc:
  swagger-ui:
    path: /api-docs
    operations-sorter: method # method: HttpMethod 순으로 정렬, alpha: 알파벳 순으로 정렬
    syntax-highlight:
      activated: true
    tags-sorter: alpha # 태그 알파벳 순으로 정렬
    doc-expansion: none
    persist-authorization: true
    display-request-duration: true

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        exclude: env, beans, redis
        include: health, prometheus
      base-path: /actuator
    jmx:
      exposure:
        exclude: "*"
  endpoint:
    health:
      show-details: always
      enabled: true
    prometheus:
      enabled: true
  health:
    redis:
      enabled: false
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
      maximum-expected-value:
        http.server.requests: 1s
