mifare:
  use: false # true: acr122 사용, false: acr122 사용 안함

  secret-key: FFFFFFFFFFFF
  debug: true

app:
  api-server-host: http://192.168.12.150:18010
  file-path: C://jsolution/jagency # 앱 파일 저장 경로
  version-url: /api/open/extensions/version/jagency # 앱 다운로드 Endpoint
  download-url: /api/open/extensions/download/jagency # 앱 다운로드 Endpoint

  tag:
    endpoint: /api/v1/room-waitings/tag
    roomId: 1
