app:
  file-server-host: https://jem.huclo.co.kr
  file-path: C://jsolution/jagency # 앱 파일 저장 경로
  version-url: /api/open/extensions/version/jagency # 앱  Endpoint
  get-extension-info-url: /api/open/extensions/jagency # 앱 정보 조회 Endpoint

file-to-db:
  active: true
  key: daedong
  company-id: 1001b2cf-642c-4da6-b61d-f921c1454a78
  file-path: C://jsolution/dbdata # 파일 경로
  api-url: https://j-erp-production.huclo.co.kr/api/v1/temperature-monitoring/j-agency/backup
